import type { TonePreset } from "./types";

export interface CameraReadyPresetRecipe {
  slug: "modern-jazz" | "modern-fusion" | "modern-ambient";
  shortName: string;
  summary: string;
  tone: TonePreset;
}

const CAMERA_TIPS = [
  "On the Quad Cortex, set USB dry/wet routing so the processed stereo feed reaches USB 1/2.",
  "In Final Cut Camera, open Settings > Audio, select Quad Cortex as the source, and choose Stereo.",
  "Monitor from the Quad Cortex headphone output instead of AirPods to avoid latency and Bluetooth routing changes.",
  "Play the loudest scene and adjust QC USB output until Final Cut Camera peaks around -12 to -6 dBFS without clipping.",
] as const;

const MODERN_JAZZ: TonePreset = {
  recording_target: "final-cut-camera",
  tone_name: "Camera Velvet Jazz",
  description:
    "A finished modern-jazz sound for direct iPhone capture: warm open-back articulation, parallel compression, subtle stereo movement, dark delay, and a filtered vintage-digital tail. Four level-matched scenes move from intimate comping to spacious fusion without needing post-production.",
  inspiration: "Contemporary chord melody, neo-soul harmony, and cinematic jazz",
  signal_chain: [
    {
      position: 1,
      row: 1,
      device_id: "douglas-shining-comp-m",
      device_name: "Douglas Shining Comp (M)",
      role: "Parallel control that preserves pick attack for phone recording",
      bypassed: false,
      parameters: {
        INPUT: 36,
        RATIO: "4",
        ATTACK: 24,
        RELEASE: 42,
        MAKEUP: 45,
        MIX: 55,
      },
    },
    {
      position: 2,
      row: 1,
      device_id: "klon",
      device_name: "Klon",
      role: "Low-gain harmonic lift for complex chords and singing lines",
      bypassed: false,
      parameters: { GAIN: 5, TREBLE: 38, LEVEL: 48 },
    },
    {
      position: 3,
      row: 1,
      device_id: "us-prince",
      device_name: "US Prince",
      role: "Warm American clean foundation with controlled low mids",
      bypassed: false,
      parameters: { VOLUME: 32, TREBLE: 34, BASS: 54 },
    },
    {
      position: 4,
      row: 1,
      device_id: "cab-2x12-us",
      device_name: "2x12 US C12",
      role: "Factory open-back American 2x12 for warm, articulate clean response",
      bypassed: false,
      parameters: {},
    },
    {
      position: 5,
      row: 1,
      device_id: "chorus-ce1",
      device_name: "Chorus CE-1",
      role: "Subtle analog width that keeps the dry note centered",
      bypassed: false,
      parameters: {
        MIX: 6,
        MODE: false,
        CHR_RATE: 13,
        VIB_RATE: 9,
        VIB_DEPTH: 8,
        WIDTH: 68,
        SYNC: false,
      },
    },
    {
      position: 6,
      row: 1,
      device_id: "analog-delay",
      device_name: "Analog Delay",
      role: "Dark repeats that duck perceptually behind the attack",
      bypassed: false,
      parameters: {
        MIX: 9,
        FEEDBACK: 18,
        MOD_DEPTH: 9,
        SYNC: false,
        TRAILS: true,
        DRIVE: 5,
        QUALITY: 72,
      },
    },
    {
      position: 7,
      row: 1,
      device_id: "vintage-digital",
      device_name: "Vintage Digital",
      role: "Polished modulated studio space with filtered tails",
      bypassed: false,
      parameters: {
        MIX: 12,
        SIZE: 54,
        PRE_DELAY: 20,
        DECAY: 42,
        HF_DAMPING: 58,
        MODULATION: 25,
        HIGH_PASS: 31,
        LOW_PASS: 54,
        FREEZE: false,
        TRAILS: true,
      },
    },
    {
      position: 8,
      row: 1,
      device_id: "plugin-parametric-4",
      device_name: "Plugin Parametric-4",
      role: "Final camera translation filter and gentle mid focus",
      bypassed: false,
      parameters: {
        HPF: 13,
        LO_GAIN: 46,
        LO_FREQ: 38,
        LO_MID_GAIN: 53,
        LO_MID_FREQ: 47,
        HI_MID_GAIN: 49,
        HI_MID_FREQ: 45,
        HI_GAIN: 46,
        HI_FREQ: 44,
        LPF: 58,
      },
    },
  ],
  scenes: [
    {
      name: "Clean",
      description: "Close, dynamic comping with just enough room to feel recorded.",
      changes: [
        { row: 1, position: 1, parameters: { MIX: 48 } },
        { row: 1, position: 2, parameters: { GAIN: 2 } },
        { row: 1, position: 3, parameters: { VOLUME: 30 } },
        { row: 1, position: 5, parameters: { MIX: 3 } },
        { row: 1, position: 6, parameters: { MIX: 6, FEEDBACK: 13 } },
        { row: 1, position: 7, parameters: { MIX: 9, DECAY: 34 } },
      ],
    },
    {
      name: "Wide",
      description: "A wider chord-melody image with a little more sustain and bloom.",
      changes: [
        { row: 1, position: 1, parameters: { MIX: 55 } },
        { row: 1, position: 2, parameters: { GAIN: 6 } },
        { row: 1, position: 3, parameters: { VOLUME: 34 } },
        { row: 1, position: 5, parameters: { MIX: 7 } },
        { row: 1, position: 6, parameters: { MIX: 11, FEEDBACK: 19 } },
        { row: 1, position: 7, parameters: { MIX: 16, DECAY: 48 } },
      ],
    },
    {
      name: "Lead",
      description: "Smooth harmonic push with present but unobtrusive repeats.",
      changes: [
        { row: 1, position: 1, parameters: { MIX: 62 } },
        { row: 1, position: 2, parameters: { GAIN: 17 } },
        { row: 1, position: 3, parameters: { VOLUME: 39 } },
        { row: 1, position: 5, parameters: { MIX: 9 } },
        { row: 1, position: 6, parameters: { MIX: 20, FEEDBACK: 27 } },
        { row: 1, position: 7, parameters: { MIX: 21, DECAY: 58 } },
      ],
    },
    {
      name: "Ambient",
      description: "Long, filtered space for intros and held chord voicings.",
      changes: [
        { row: 1, position: 1, parameters: { MIX: 56 } },
        { row: 1, position: 2, parameters: { GAIN: 9 } },
        { row: 1, position: 3, parameters: { VOLUME: 33 } },
        { row: 1, position: 5, parameters: { MIX: 11 } },
        { row: 1, position: 6, parameters: { MIX: 25, FEEDBACK: 36 } },
        { row: 1, position: 7, parameters: { MIX: 32, DECAY: 72 } },
      ],
    },
  ],
  tips: [
    ...CAMERA_TIPS,
    "Use the neck pickup with the guitar tone around 7 for Clean and Wide; open it up for Lead.",
    "If your guitar is bright, reduce amp TREBLE before adding bass so complex chords remain clear.",
  ],
  genre_tags: ["modern-jazz", "neo-soul", "fusion", "camera-ready"],
};

const MODERN_FUSION: TonePreset = {
  recording_target: "final-cut-camera",
  tone_name: "Camera Neon Fusion",
  description:
    "A focused modern-fusion preset with a parallel front end, tight Mark-style gain, filtered Crystal Delay, and a smooth studio plate. Its four scenes retain punch and consistent recording headroom from articulate rhythm to an expansive lead.",
  inspiration: "Modern instrumental fusion, progressive phrasing, and polished live sessions",
  signal_chain: [
    {
      position: 1,
      row: 1,
      device_id: "douglas-shining-comp-m",
      device_name: "Douglas Shining Comp (M)",
      role: "Parallel compression for even camera levels without flattened attack",
      bypassed: false,
      parameters: {
        INPUT: 32,
        RATIO: "4",
        ATTACK: 29,
        RELEASE: 38,
        MAKEUP: 44,
        MIX: 48,
      },
    },
    {
      position: 2,
      row: 1,
      device_id: "ts808",
      device_name: "TS808",
      role: "Low-drive mid focus that tightens the amp response",
      bypassed: false,
      parameters: { OVERDRIVE: 8, TONE: 51, LEVEL: 61 },
    },
    {
      position: 3,
      row: 1,
      device_id: "ca-jp2c",
      device_name: "CA JP-2C",
      role: "Responsive Mark-style fusion voice with controlled low end",
      bypassed: false,
      parameters: {
        GAIN: 42,
        MASTER: 31,
        BASS: 34,
        MID: 54,
        TREBLE: 55,
        PRESENCE: 47,
        GAIN_PULL: false,
        SHRED: false,
      },
    },
    {
      position: 4,
      row: 1,
      device_id: "cab-4x12-mesa-recto",
      device_name: "4x12 CA Recto",
      role: "Tight factory V30 voice with dependable hardware availability",
      bypassed: false,
      parameters: {},
    },
    {
      position: 5,
      row: 1,
      device_id: "plugin-parametric-4",
      device_name: "Plugin Parametric-4",
      role: "Low-cut cleanup and broad mid shaping for phone translation",
      bypassed: false,
      parameters: {
        HPF: 16,
        LO_GAIN: 43,
        LO_FREQ: 42,
        LO_MID_GAIN: 53,
        LO_MID_FREQ: 49,
        HI_MID_GAIN: 51,
        HI_MID_FREQ: 43,
        HI_GAIN: 45,
        HI_FREQ: 48,
        LPF: 54,
      },
    },
    {
      position: 6,
      row: 1,
      device_id: "crystal-delay",
      device_name: "Crystal Delay",
      role: "Wide filtered repeats with restrained upper harmonics",
      bypassed: false,
      parameters: {
        MIX: 12,
        SYNC: true,
        SYNC_NOTE_L: "1/8D",
        SYNC_NOTE_R: "1/4",
        CRYSTAL_1_PAN: 24,
        CRYSTAL_2_PAN: 76,
        CRYSTAL_1_GAIN: 33,
        CRYSTAL_2_GAIN: 27,
        MODE: true,
        FEEDBACK: 25,
        LOW_PASS: 48,
        HIGH_PASS: 28,
        TRAILS: true,
      },
    },
    {
      position: 7,
      row: 1,
      device_id: "plate-reverb",
      device_name: "Plate Reverb",
      role: "Smooth studio tail that keeps the guitar forward",
      bypassed: false,
      parameters: {
        MIX: 12,
        DECAY: 42,
        PRE_DELAY: 21,
        HIGH_PASS: 31,
        LOW_PASS: 52,
        MOD_DEPTH: 19,
        TRAILS: true,
      },
    },
  ],
  scenes: [
    {
      name: "Clean",
      description: "Low-gain, articulate fusion chords with a short studio tail.",
      changes: [
        { row: 1, position: 2, parameters: { OVERDRIVE: 2, LEVEL: 48 } },
        { row: 1, position: 3, parameters: { GAIN: 22, MASTER: 31 } },
        { row: 1, position: 6, parameters: { MIX: 5, FEEDBACK: 15 } },
        { row: 1, position: 7, parameters: { MIX: 9, DECAY: 32 } },
      ],
    },
    {
      name: "Wide",
      description: "Edge-of-breakup rhythm with stereo rhythmic detail.",
      changes: [
        { row: 1, position: 2, parameters: { OVERDRIVE: 6, LEVEL: 56 } },
        { row: 1, position: 3, parameters: { GAIN: 35, MASTER: 30 } },
        { row: 1, position: 6, parameters: { MIX: 14, FEEDBACK: 23 } },
        { row: 1, position: 7, parameters: { MIX: 13, DECAY: 41 } },
      ],
    },
    {
      name: "Lead",
      description: "Focused singing gain with enough delay to connect phrases.",
      changes: [
        { row: 1, position: 2, parameters: { OVERDRIVE: 10, LEVEL: 64 } },
        { row: 1, position: 3, parameters: { GAIN: 47, MASTER: 28 } },
        { row: 1, position: 6, parameters: { MIX: 23, FEEDBACK: 31 } },
        { row: 1, position: 7, parameters: { MIX: 18, DECAY: 52 } },
      ],
    },
    {
      name: "Ambient",
      description: "A wider harmonic tail for slower melodic and volume-swell work.",
      changes: [
        { row: 1, position: 2, parameters: { OVERDRIVE: 7, LEVEL: 58 } },
        { row: 1, position: 3, parameters: { GAIN: 39, MASTER: 26 } },
        { row: 1, position: 6, parameters: { MIX: 34, FEEDBACK: 43 } },
        { row: 1, position: 7, parameters: { MIX: 27, DECAY: 68 } },
      ],
    },
  ],
  tips: [
    ...CAMERA_TIPS,
    "Use Clean or Wide for double-stops; Lead is intentionally level-compensated by lowering MASTER as gain rises.",
    "If the Recto cab feels too dense on your guitar, lower amp BASS before changing the final EQ.",
  ],
  genre_tags: ["fusion", "progressive", "lead", "camera-ready"],
};

const MODERN_AMBIENT: TonePreset = {
  recording_target: "final-cut-camera",
  tone_name: "Camera Aurora Space",
  description:
    "A cinematic ambient preset that layers subtle detuned voices, Crystal Delay, vintage digital depth, and shimmer around a warm American clean core. The wettest scene lowers the amp level to protect iPhone recording headroom while preserving a centered direct note.",
  inspiration: "Modern ambient guitar, spacious soundtrack cues, and glassy post-rock",
  signal_chain: [
    {
      position: 1,
      row: 1,
      device_id: "douglas-shining-comp-m",
      device_name: "Douglas Shining Comp (M)",
      role: "Gentle parallel sustain before the ambient layers",
      bypassed: false,
      parameters: {
        INPUT: 30,
        RATIO: "4",
        ATTACK: 31,
        RELEASE: 49,
        MAKEUP: 43,
        MIX: 46,
      },
    },
    {
      position: 2,
      row: 1,
      device_id: "us-twn-rev",
      device_name: "US TWN Rev",
      role: "Wide-headroom American clean foundation",
      bypassed: false,
      parameters: {
        VOLUME: 30,
        BRIGHT: false,
        BASS: 44,
        MID: 53,
        TREBLE: 46,
      },
    },
    {
      position: 3,
      row: 1,
      device_id: "cab-2x12-us",
      device_name: "2x12 US C12",
      role: "Factory open-back American 2x12 for a portable clean foundation",
      bypassed: false,
      parameters: {},
    },
    {
      position: 4,
      row: 1,
      device_id: "multivoicer",
      device_name: "Multivoicer",
      role: "Quiet detuned unison pair for stereo scale and movement",
      bypassed: false,
      parameters: {
        DI_LEVEL: 72,
        KEY: "C",
        SCALE: "Chromatic",
        QUANTIZE: false,
        V1_ACTIVE: true,
        V1_LEVEL: 35,
        V1_INTERVAL: "Root",
        V1_DETUNE: 46,
        V1_DELAY: 18,
        V1_PAN: 24,
        V2_ACTIVE: true,
        V2_LEVEL: 35,
        V2_INTERVAL: "Root",
        V2_DETUNE: 54,
        V2_DELAY: 25,
        V2_PAN: 76,
        HIGH_PASS: 24,
        LOW_PASS: 58,
        TONE: 48,
        GLISSANDO: 8,
        UNISON: 34,
        WIDTH: 78,
        OUTPUT: 44,
      },
    },
    {
      position: 5,
      row: 1,
      device_id: "crystal-delay",
      device_name: "Crystal Delay",
      role: "Filtered stereo crystals behind the direct attack",
      bypassed: false,
      parameters: {
        MIX: 18,
        SYNC: true,
        SYNC_NOTE_L: "1/8D",
        SYNC_NOTE_R: "1/2",
        CRYSTAL_1_PAN: 18,
        CRYSTAL_2_PAN: 82,
        CRYSTAL_1_GAIN: 30,
        CRYSTAL_2_GAIN: 24,
        MODE: true,
        FEEDBACK: 33,
        LOW_PASS: 45,
        HIGH_PASS: 34,
        TRAILS: true,
      },
    },
    {
      position: 6,
      row: 1,
      device_id: "vintage-digital",
      device_name: "Vintage Digital",
      role: "Modulated mid-length room that joins the delay and shimmer",
      bypassed: false,
      parameters: {
        MIX: 20,
        SIZE: 68,
        PRE_DELAY: 26,
        DECAY: 61,
        HF_DAMPING: 63,
        MODULATION: 34,
        HIGH_PASS: 37,
        LOW_PASS: 49,
        FREEZE: false,
        TRAILS: true,
      },
    },
    {
      position: 7,
      row: 1,
      device_id: "shimmer-reverb",
      device_name: "Shimmer Reverb",
      role: "Restrained octave bloom for the far edge of the soundstage",
      bypassed: false,
      parameters: {
        MIX: 14,
        DECAY: 63,
        BRIGHTNESS: 42,
        FEEDBACK: 33,
        PITCH: 61,
        TRAILS: true,
      },
    },
    {
      position: 8,
      row: 1,
      device_id: "plugin-parametric-4",
      device_name: "Plugin Parametric-4",
      role: "Final wet-tail cleanup for small speakers and mono compatibility",
      bypassed: false,
      parameters: {
        HPF: 17,
        LO_GAIN: 44,
        LO_FREQ: 41,
        LO_MID_GAIN: 52,
        LO_MID_FREQ: 48,
        HI_MID_GAIN: 49,
        HI_MID_FREQ: 44,
        HI_GAIN: 44,
        HI_FREQ: 42,
        LPF: 52,
      },
    },
  ],
  scenes: [
    {
      name: "Clean",
      description: "Centered direct sound with a small halo and short tail.",
      changes: [
        { row: 1, position: 2, parameters: { VOLUME: 30 } },
        { row: 1, position: 4, parameters: { V1_LEVEL: 24, V2_LEVEL: 24 } },
        { row: 1, position: 5, parameters: { MIX: 7, FEEDBACK: 18 } },
        { row: 1, position: 6, parameters: { MIX: 10, DECAY: 36 } },
        { row: 1, position: 7, parameters: { MIX: 5, DECAY: 38 } },
      ],
    },
    {
      name: "Wide",
      description: "Detuned stereo width and a clear rhythmic ambient bed.",
      changes: [
        { row: 1, position: 2, parameters: { VOLUME: 29 } },
        { row: 1, position: 4, parameters: { V1_LEVEL: 36, V2_LEVEL: 36 } },
        { row: 1, position: 5, parameters: { MIX: 19, FEEDBACK: 30 } },
        { row: 1, position: 6, parameters: { MIX: 21, DECAY: 57 } },
        { row: 1, position: 7, parameters: { MIX: 13, DECAY: 59 } },
      ],
    },
    {
      name: "Lead",
      description: "Present melodic sustain with stereo tails kept behind the note.",
      changes: [
        { row: 1, position: 2, parameters: { VOLUME: 28 } },
        { row: 1, position: 4, parameters: { V1_LEVEL: 40, V2_LEVEL: 40 } },
        { row: 1, position: 5, parameters: { MIX: 25, FEEDBACK: 36 } },
        { row: 1, position: 6, parameters: { MIX: 26, DECAY: 66 } },
        { row: 1, position: 7, parameters: { MIX: 20, DECAY: 70 } },
      ],
    },
    {
      name: "Ambient",
      description: "Deep cinematic wash with compensated dry level and long filtered decay.",
      changes: [
        { row: 1, position: 2, parameters: { VOLUME: 25 } },
        { row: 1, position: 4, parameters: { V1_LEVEL: 45, V2_LEVEL: 45 } },
        { row: 1, position: 5, parameters: { MIX: 38, FEEDBACK: 48 } },
        { row: 1, position: 6, parameters: { MIX: 39, DECAY: 78 } },
        { row: 1, position: 7, parameters: { MIX: 31, DECAY: 82 } },
      ],
    },
  ],
  tips: [
    ...CAMERA_TIPS,
    "Pick nearer the neck and let rests breathe; the longest scene is designed around space between notes.",
    "Ambient lowers amp VOLUME as three wet layers rise, reducing the chance of an unexpected camera-level jump.",
  ],
  genre_tags: ["ambient", "cinematic", "post-rock", "camera-ready"],
};

export const CAMERA_READY_PRESETS: readonly CameraReadyPresetRecipe[] = [
  {
    slug: "modern-jazz",
    shortName: "Modern Jazz",
    summary: "Warm open-back detail, gentle width, and four balanced performance scenes.",
    tone: MODERN_JAZZ,
  },
  {
    slug: "modern-fusion",
    shortName: "Modern Fusion",
    summary: "Tight articulate gain with Crystal Delay and polished studio space.",
    tone: MODERN_FUSION,
  },
  {
    slug: "modern-ambient",
    shortName: "Modern Ambient",
    summary: "Detuned stereo voices and deep filtered cinematic layers.",
    tone: MODERN_AMBIENT,
  },
] as const;
