import type { TonePluginLicense } from "./types";

export type DeviceCategory =
  | "amp"
  | "cab"
  | "drive"
  | "delay"
  | "reverb"
  | "modulation"
  | "compressor"
  | "eq"
  | "pitch"
  | "synth"
  | "wah"
  | "gate"
  | "utility";

export interface Device {
  id: string;
  name: string;
  category: DeviceCategory;
  basedOn: string;
  description: string;
  tags: string[];
  /** Factory model ID confirmed for the firmware compatibility gate. */
  qcModelId?: number;
  /** Safe writable controls exposed to tone generation. */
  parameters?: readonly DeviceParameter[];
  /** False for controls that require a user-selected device resource. */
  generatable?: boolean;
  /** Licensed plugin that must be explicitly enabled for generation. */
  requiresPlugin?: TonePluginLicense;
}

export interface DeviceParameter {
  name: string;
  kind: "position" | "switch" | "text";
  /** Selects one duplicate-named ModelRepo parameter unambiguously. */
  qcParameterIndex?: number;
}

const position = (name: string): DeviceParameter => ({ name, kind: "position" });
const toggle = (name: string): DeviceParameter => ({ name, kind: "switch" });
const text = (name: string, qcParameterIndex?: number): DeviceParameter => ({
  name,
  kind: "text",
  qcParameterIndex,
});
const STANDARD_AMP = [
  position("GAIN"),
  position("BASS"),
  position("MID"),
  position("TREBLE"),
  position("MASTER"),
  position("PRESENCE"),
] as const;
const SIMPLE_FENDER_AMP = [
  position("VOLUME"),
  position("TREBLE"),
  position("BASS"),
] as const;
const STANDARD_DELAY = [
  position("MIX"),
  position("FEEDBACK"),
  position("MOD_DEPTH"),
  toggle("SYNC"),
  toggle("TRAILS"),
] as const;
const STANDARD_REVERB = [
  position("DECAY"),
  position("PRE_DELAY"),
  position("HIGH_PASS"),
  position("LOW_PASS"),
  position("MIX"),
  toggle("TRAILS"),
] as const;
const CAB_CONTROLS = [] as const;

// Tone-design reference library. Entries with qcModelId + parameters are
// transfer profiles backed by the d14e factory catalog and live verification.
// Only those
// entries are exposed to generation; the rest remain available to older saved
// tone plans and can be profiled without changing their stable IDs.
export const QC_DEVICES: Device[] = [
  // ===== AMPLIFIERS =====
  // Marshall-based
  {
    id: "brit-2203",
    name: "Brit 2203",
    category: "amp",
    basedOn: "Marshall JCM800 2203",
    description: "Classic British high-gain. Iconic crunch to hard rock distortion.",
    tags: ["british", "high-gain", "rock", "metal", "crunch", "marshall"],
    qcModelId: 1001,
    parameters: STANDARD_AMP,
  },
  {
    id: "brit-plexi-100",
    name: "Brit Plexi 100",
    category: "amp",
    basedOn: "Marshall Super Lead 1959",
    description: "Legendary plexi tone. Classic rock crunch with harmonic richness.",
    tags: ["british", "classic-rock", "crunch", "vintage", "marshall", "plexi"],
    qcModelId: 1091,
    parameters: STANDARD_AMP.filter((parameter) => parameter.name !== "MASTER"),
  },
  {
    id: "brit-800",
    name: "Brit 800",
    category: "amp",
    basedOn: "Marshall JCM800 2204",
    description: "Single-channel JCM800. Raw British rock tone.",
    tags: ["british", "rock", "crunch", "marshall"],
  },
  {
    id: "brit-900",
    name: "Brit 900",
    category: "amp",
    basedOn: "Marshall JCM900",
    description: "Higher gain Marshall. Bridge between classic and modern British tone.",
    tags: ["british", "high-gain", "rock", "metal", "marshall"],
  },
  {
    id: "brit-silver",
    name: "Brit Silver",
    category: "amp",
    basedOn: "Marshall Silver Jubilee 2555",
    description: "Versatile Marshall with clip switch. Slash's iconic tone.",
    tags: ["british", "rock", "hard-rock", "marshall", "slash"],
  },
  {
    id: "brit-j45",
    name: "Brit J45",
    category: "amp",
    basedOn: "Marshall JTM45",
    description: "Early Marshall. Warm, bluesy, with Fender-like clean headroom.",
    tags: ["british", "blues", "vintage", "clean", "marshall"],
  },

  // Mesa Boogie-based
  {
    id: "ca-rectifire",
    name: "CA Rectifire",
    category: "amp",
    basedOn: "Mesa Boogie Dual Rectifier",
    description: "Modern high-gain. Thick, saturated distortion for metal and hard rock.",
    tags: ["american", "high-gain", "metal", "hard-rock", "mesa", "rectifier"],
    qcModelId: 1018,
    parameters: STANDARD_AMP,
  },
  {
    id: "ca-rectifire-v",
    name: "CA Rectifire Vintage",
    category: "amp",
    basedOn: "Mesa Boogie Dual Rectifier (Vintage mode)",
    description: "Rectifier with vintage voicing. Slightly less gain, more midrange focus.",
    tags: ["american", "high-gain", "rock", "metal", "mesa", "rectifier"],
  },
  {
    id: "ca-mark-iic",
    name: "CA Mark IIC+",
    category: "amp",
    basedOn: "Mesa Boogie Mark IIC+",
    description: "The holy grail of lead tones. Metallica's Master of Puppets tone.",
    tags: ["american", "high-gain", "metal", "lead", "mesa", "metallica"],
  },
  {
    id: "ca-mark-iv",
    name: "CA Mark IV",
    category: "amp",
    basedOn: "Mesa Boogie Mark IV",
    description: "Versatile 3-channel Mesa. Clean to crushing gain.",
    tags: ["american", "high-gain", "versatile", "metal", "mesa"],
  },
  {
    id: "ca-lonestar",
    name: "CA Lonestar",
    category: "amp",
    basedOn: "Mesa Boogie Lone Star",
    description: "Boutique clean and overdrive. Warm, complex harmonics.",
    tags: ["american", "clean", "overdrive", "boutique", "mesa"],
  },
  {
    id: "ca-jp2c",
    name: "CA JP-2C",
    category: "amp",
    basedOn: "Mesa Boogie JP-2C",
    description: "John Petrucci signature. Ultra-tight high-gain with surgical precision.",
    tags: ["american", "high-gain", "metal", "progressive", "mesa", "petrucci"],
    qcModelId: 1141,
    parameters: [
      position("GAIN"),
      position("MASTER"),
      position("BASS"),
      position("MID"),
      position("TREBLE"),
      position("PRESENCE"),
      toggle("GAIN_PULL"),
      toggle("SHRED"),
    ],
  },

  // Fender-based
  {
    id: "us-dlx-rev",
    name: "US DLX Rev",
    category: "amp",
    basedOn: "Fender Deluxe Reverb '65",
    description: "The studio workhorse. Warm cleans with beautiful spring reverb.",
    tags: ["american", "clean", "blues", "country", "fender", "studio"],
    qcModelId: 1167,
    parameters: SIMPLE_FENDER_AMP,
  },
  {
    id: "us-twn-rev",
    name: "US TWN Rev",
    category: "amp",
    basedOn: "Fender Twin Reverb '65",
    description: "Pristine headroom. Crystal-clean Fender tone for any genre.",
    tags: ["american", "clean", "headroom", "fender", "jazz", "country"],
    qcModelId: 1084,
    parameters: [
      position("VOLUME"),
      toggle("BRIGHT"),
      position("BASS"),
      position("MID"),
      position("TREBLE"),
    ],
  },
  {
    id: "us-prince",
    name: "US Prince",
    category: "amp",
    basedOn: "Fender Princeton Reverb",
    description: "Small combo with big tone. Sweet breakup at lower volumes.",
    tags: ["american", "clean", "blues", "breakup", "fender"],
    qcModelId: 1120,
    parameters: SIMPLE_FENDER_AMP,
  },
  {
    id: "us-bman",
    name: "US BMan",
    category: "amp",
    basedOn: "Fender Bassman",
    description: "The original. Warm, fat tone that inspired Marshall amps.",
    tags: ["american", "clean", "blues", "vintage", "fender", "warm"],
  },

  // Vox-based
  {
    id: "uk-c30",
    name: "UK C30",
    category: "amp",
    basedOn: "Vox AC30",
    description: "Chimey British tone. Class A warmth with jangly top end.",
    tags: ["british", "chime", "jangle", "indie", "vox", "class-a"],
    qcModelId: 1011,
    parameters: [
      position("VOLUME"),
      toggle("BOOST"),
      position("BASS"),
      position("TREBLE"),
      position("TONE_CUT"),
    ],
  },
  {
    id: "uk-c15",
    name: "UK C15",
    category: "amp",
    basedOn: "Vox AC15",
    description: "Smaller Vox. Earlier breakup, great for blues and indie.",
    tags: ["british", "chime", "blues", "indie", "vox"],
    qcModelId: 1128,
    parameters: [
      position("VOLUME"),
      position("BASS"),
      position("TREBLE"),
      position("TONE_CUT"),
    ],
  },

  // High-gain modern
  {
    id: "ev-101-iii",
    name: "EV 101 III",
    category: "amp",
    basedOn: "EVH 5150 III",
    description: "Eddie Van Halen's modern evolution. 3 channels, clean to crushing.",
    tags: ["american", "high-gain", "metal", "rock", "evh", "5150"],
    qcModelId: 1119,
    parameters: [...STANDARD_AMP, position("RESONANCE")],
  },
  {
    id: "pv-505",
    name: "PV 505",
    category: "amp",
    basedOn: "Peavey 5150",
    description: "The original 5150. Aggressive high-gain, metal standard.",
    tags: ["american", "high-gain", "metal", "aggressive", "peavey", "5150"],
    qcModelId: 1002,
    parameters: [...STANDARD_AMP, position("DEPTH")],
  },
  {
    id: "bogna-uber",
    name: "Bogna Uber",
    category: "amp",
    basedOn: "Bogner Uberschall",
    description: "Extreme high-gain. Tight low end, aggressive mids. Modern metal.",
    tags: ["german", "high-gain", "metal", "tight", "bogner"],
  },
  {
    id: "bogna-xtc",
    name: "Bogna XTC",
    category: "amp",
    basedOn: "Bogner Ecstasy",
    description: "Versatile boutique. Beautiful cleans through to high-gain lead.",
    tags: ["german", "versatile", "boutique", "bogner", "rock"],
  },
  {
    id: "d-cell-vh4",
    name: "D-Cell VH4",
    category: "amp",
    basedOn: "Diezel VH4",
    description: "German high-gain precision. 4 channels, tight and articulate.",
    tags: ["german", "high-gain", "metal", "tight", "diezel"],
    qcModelId: 1147,
    parameters: [...STANDARD_AMP, position("DEEP")],
  },
  {
    id: "d-cell-herbert",
    name: "D-Cell Herbert",
    category: "amp",
    basedOn: "Diezel Herbert",
    description: "3-channel Diezel. Massive low end, scooped mids available.",
    tags: ["german", "high-gain", "metal", "diezel"],
  },
  {
    id: "freeman-be",
    name: "Freeman BE",
    category: "amp",
    basedOn: "Friedman BE-100",
    description: "Hot-rodded Marshall on steroids. Modern rock/metal workhorse.",
    tags: ["american", "high-gain", "rock", "metal", "friedman", "modern-marshall"],
  },
  {
    id: "freeman-hbe",
    name: "Freeman HBE",
    category: "amp",
    basedOn: "Friedman HBE",
    description: "Friedman with more gain. Harmonically rich distortion.",
    tags: ["american", "high-gain", "metal", "friedman"],
  },
  {
    id: "revv-gen-red",
    name: "REVV Gen Red",
    category: "amp",
    basedOn: "REVV Generator 120 Red Channel",
    description: "Modern high-gain. Tight, focused, and aggressive.",
    tags: ["canadian", "high-gain", "metal", "modern", "revv", "djent"],
  },
  {
    id: "solo-100",
    name: "Solo 100",
    category: "amp",
    basedOn: "Soldano SLO-100",
    description: "The first modern high-gain amp. Rich, creamy lead tone.",
    tags: ["american", "high-gain", "lead", "rock", "soldano"],
    qcModelId: 1150,
    parameters: STANDARD_AMP,
  },
  {
    id: "cali-texas",
    name: "Cali Texas",
    category: "amp",
    basedOn: "Mesa Boogie Lonestar Special",
    description: "Texas blues meets California tone. Warm overdrive.",
    tags: ["american", "blues", "overdrive", "mesa"],
  },
  {
    id: "watt-dr103",
    name: "Watt DR103",
    category: "amp",
    basedOn: "Hiwatt DR103",
    description: "Clean British power. Pete Townshend and David Gilmour's choice.",
    tags: ["british", "clean", "powerful", "hiwatt", "gilmour"],
    qcModelId: 1064,
    parameters: STANDARD_AMP,
  },
  {
    id: "match-d30",
    name: "Match D30",
    category: "amp",
    basedOn: "Matchless DC-30",
    description: "Boutique Class A. Rich, 3D cleans with musical breakup.",
    tags: ["american", "clean", "boutique", "class-a", "matchless"],
  },
  {
    id: "citrus-roc50",
    name: "Citrus Roc50",
    category: "amp",
    basedOn: "Orange Rockerverb 50",
    description: "British grit with a modern voice. Rock and stoner tones.",
    tags: ["british", "rock", "stoner", "orange"],
  },
  {
    id: "uber-2ch",
    name: "Uber 2CH",
    category: "amp",
    basedOn: "Bogner Uberschall 2-Channel",
    description: "Refined Uberschall. Channel 2 is modern metal nirvana.",
    tags: ["german", "high-gain", "metal", "bogner"],
  },
  {
    id: "das-benzin",
    name: "Das Benzin",
    category: "amp",
    basedOn: "Diezel-style",
    description: "German high-gain with industrial edge. Perfect for Rammstein-style tones.",
    tags: ["german", "high-gain", "industrial", "metal", "rammstein"],
  },
  {
    id: "rabea-clean",
    name: "Rabea Clean",
    category: "amp",
    basedOn: "Archetype Rabea X clean amplifier",
    description:
      "Wide, high-headroom plugin amp for articulate cleans, synth layers, and ambient guitar.",
    tags: ["rabea-x", "plugin", "clean", "ambient", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 1187,
    parameters: [
      position("VOLUME"),
      position("BASS"),
      position("MIDDLE"),
      position("TREBLE"),
      toggle("HIGH_BOOST"),
      toggle("MID_BOOST"),
      position("OUTPUT"),
    ],
  },
  {
    id: "rabea-crunch",
    name: "Rabea Crunch",
    category: "amp",
    basedOn: "Archetype Rabea X crunch amplifier",
    description:
      "Modern British-style crunch with selectable power tubes and focused boost modes.",
    tags: ["rabea-x", "plugin", "crunch", "british", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 1185,
    parameters: [
      toggle("MOD"),
      position("GAIN"),
      position("BASS"),
      position("MIDDLE"),
      position("TREBLE"),
      position("MASTER"),
      position("DEPTH"),
      toggle("HIGH_BOOST"),
      toggle("MID_BOOST"),
      text("TUBE"),
      position("OUTPUT"),
    ],
  },
  {
    id: "rabea-lead",
    name: "Rabea Lead",
    category: "amp",
    basedOn: "Archetype Rabea X lead amplifier",
    description:
      "Tight, saturated modern lead amp with strong note definition and controllable depth.",
    tags: ["rabea-x", "plugin", "lead", "high-gain", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 1186,
    parameters: [
      toggle("MOD"),
      position("GAIN"),
      position("BASS"),
      position("MIDDLE"),
      position("TREBLE"),
      position("MASTER"),
      position("DEPTH"),
      position("TIGHT"),
      position("PRESENCE"),
      text("TUBE"),
      position("OUTPUT"),
    ],
  },

  // ===== DRIVE / OVERDRIVE / DISTORTION / FUZZ / BOOST =====
  {
    id: "rabea-paragon-overdrive",
    name: "Rabea Paragon Overdrive",
    category: "drive",
    basedOn: "Archetype Rabea X Paragon overdrive",
    description:
      "Broadband modern or vintage overdrive for pushing Rabea amps without losing low-end authority.",
    tags: ["rabea-x", "plugin", "overdrive", "boost", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 48,
    parameters: [
      position("DRIVE"),
      position("BASS"),
      position("TREBLE"),
      position("LEVEL"),
      text("MODE"),
    ],
  },
  {
    id: "rabea-colossus-fuzz",
    name: "Rabea Colossus Fuzz",
    category: "drive",
    basedOn: "Archetype Rabea X Colossus fuzz",
    description:
      "Large, harmonically dense fuzz with modern and vintage voicings.",
    tags: ["rabea-x", "plugin", "fuzz", "experimental", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 47,
    parameters: [
      text("MODE"),
      position("FUZZ"),
      position("BASS"),
      position("TREBLE"),
      position("LEVEL"),
    ],
  },
  {
    id: "ts808",
    name: "TS808",
    category: "drive",
    basedOn: "Ibanez Tube Screamer TS808",
    description: "The iconic mid-hump overdrive. Perfect in front of high-gain amps.",
    tags: ["overdrive", "mid-boost", "tube-screamer", "stacking"],
    qcModelId: 27,
    parameters: [
      position("OVERDRIVE"),
      position("TONE"),
      position("LEVEL"),
    ],
  },
  {
    id: "ts9",
    name: "TS9",
    category: "drive",
    basedOn: "Ibanez Tube Screamer TS9",
    description: "Slightly brighter Tube Screamer variant.",
    tags: ["overdrive", "mid-boost", "tube-screamer"],
  },
  {
    id: "klon",
    name: "Klon",
    category: "drive",
    basedOn: "Klon Centaur",
    description: "Transparent overdrive. Adds grit without losing your tone.",
    tags: ["overdrive", "transparent", "boost", "klon"],
    qcModelId: 1,
    parameters: [position("GAIN"), position("TREBLE"), position("LEVEL")],
  },
  {
    id: "morning-glory",
    name: "Morning Glory",
    category: "drive",
    basedOn: "JHS Morning Glory",
    description: "Marshall-in-a-box overdrive. Blues crunch to medium gain.",
    tags: ["overdrive", "blues", "crunch", "marshall-style"],
  },
  {
    id: "king-of-tone",
    name: "King of Tone",
    category: "drive",
    basedOn: "Analogman King of Tone",
    description: "Dual-stage overdrive. Versatile, from clean boost to crunchy drive.",
    tags: ["overdrive", "versatile", "boost", "blues"],
  },
  {
    id: "blues-driver",
    name: "Blues Driver",
    category: "drive",
    basedOn: "Boss BD-2",
    description: "Open, dynamic overdrive. Great response to picking dynamics.",
    tags: ["overdrive", "blues", "dynamic", "boss"],
    qcModelId: 18,
    parameters: [position("GAIN"), position("TONE"), position("VOLUME")],
  },
  {
    id: "ocd",
    name: "OCD",
    category: "drive",
    basedOn: "Fulltone OCD",
    description: "Amp-like overdrive. Thick, harmonically rich drive.",
    tags: ["overdrive", "amp-like", "rock"],
    qcModelId: 2,
    parameters: [
      position("DRIVE"),
      toggle("PEAK"),
      position("TONE"),
      position("VOLUME"),
    ],
  },
  {
    id: "rat",
    name: "RAT",
    category: "drive",
    basedOn: "Pro Co RAT",
    description: "Gritty distortion. From mild crunch to heavy fuzz-like distortion.",
    tags: ["distortion", "gritty", "rock", "grunge"],
    qcModelId: 4,
    parameters: [
      position("DISTORTION"),
      position("FILTER"),
      position("VOLUME"),
    ],
  },
  {
    id: "ds1",
    name: "DS-1",
    category: "drive",
    basedOn: "Boss DS-1",
    description: "Classic distortion. Bright, cutting tone used by Kurt Cobain.",
    tags: ["distortion", "bright", "grunge", "rock", "boss"],
    qcModelId: 10,
    parameters: [
      position("DISTORTION"),
      position("TONE"),
      position("LEVEL"),
    ],
  },
  {
    id: "metal-zone",
    name: "Metal Zone",
    category: "drive",
    basedOn: "Boss MT-2",
    description: "Extreme distortion with parametric EQ. Modern metal in a pedal.",
    tags: ["distortion", "metal", "extreme", "boss"],
  },
  {
    id: "big-muff",
    name: "Big Muff",
    category: "drive",
    basedOn: "Electro-Harmonix Big Muff Pi",
    description: "Iconic fuzz. Thick, sustaining wall of fuzz for leads and drones.",
    tags: ["fuzz", "sustain", "grunge", "shoegaze", "ehx"],
    qcModelId: 15,
    parameters: [
      position("SUSTAIN"),
      position("TONE"),
      position("VOLUME"),
    ],
  },
  {
    id: "fuzz-face",
    name: "Fuzz Face",
    category: "drive",
    basedOn: "Dallas Arbiter Fuzz Face",
    description: "Vintage germanium fuzz. Hendrix and classic psychedelic tones.",
    tags: ["fuzz", "vintage", "hendrix", "psychedelic"],
    qcModelId: 22,
    parameters: [position("FUZZ"), position("VOLUME")],
  },
  {
    id: "precision-drive",
    name: "Precision Drive",
    category: "drive",
    basedOn: "Horizon Devices Precision Drive",
    description: "Tight gate + overdrive. Designed for modern metal and djent.",
    tags: ["overdrive", "gate", "metal", "djent", "tight"],
  },
  {
    id: "ep-boost",
    name: "EP Boost",
    category: "drive",
    basedOn: "Xotic EP Booster",
    description: "Clean boost with subtle coloring. Adds life and presence.",
    tags: ["boost", "clean", "always-on"],
  },

  // ===== DELAY =====
  {
    id: "digital-delay",
    name: "Digital Delay",
    category: "delay",
    basedOn: "Generic Digital Delay",
    description: "Clean, precise repeats. Versatile studio delay.",
    tags: ["digital", "clean", "versatile"],
    qcModelId: 6005,
    parameters: STANDARD_DELAY,
  },
  {
    id: "analog-delay",
    name: "Analog Delay",
    category: "delay",
    basedOn: "Boss DM-2 / MXR Carbon Copy style",
    description: "Warm, dark repeats that sit behind the dry signal.",
    tags: ["analog", "warm", "dark"],
    qcModelId: 6001,
    parameters: [
      ...STANDARD_DELAY,
      position("DRIVE"),
      position("QUALITY"),
    ],
  },
  {
    id: "tape-delay",
    name: "Tape Delay",
    category: "delay",
    basedOn: "Maestro Echoplex / Roland Space Echo",
    description: "Tape-style warble and degradation. Organic, vintage delay.",
    tags: ["tape", "vintage", "warm", "modulated"],
    qcModelId: 6007,
    parameters: [
      position("MIX"),
      position("FEEDBACK"),
      position("WOW"),
      position("FLUTTER"),
      toggle("SYNC"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "ping-pong-delay",
    name: "Ping Pong Delay",
    category: "delay",
    basedOn: "Stereo Ping Pong",
    description: "Bouncing left/right stereo delay. Great for ambient textures.",
    tags: ["stereo", "ambient", "wide"],
    qcModelId: 6002,
    parameters: [
      position("MIX"),
      position("FEEDBACK"),
      position("TONE"),
      position("STEREO_WIDTH"),
      toggle("SYNC"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "reverse-delay",
    name: "Reverse Delay",
    category: "delay",
    basedOn: "Reverse Delay",
    description: "Reversed repeats for ethereal, otherworldly textures.",
    tags: ["reverse", "ambient", "experimental"],
  },
  {
    id: "slapback-delay",
    name: "Slapback Delay",
    category: "delay",
    basedOn: "Slapback Delay",
    description: "Short single repeat. Rockabilly, country, and vintage rock.",
    tags: ["slapback", "vintage", "country", "rockabilly"],
    qcModelId: 6009,
    parameters: [
      ...STANDARD_DELAY,
      position("DRIVE"),
      position("QUALITY"),
    ],
  },
  {
    id: "multi-tap-delay",
    name: "Multi-Tap Delay",
    category: "delay",
    basedOn: "Multi-Tap",
    description: "Multiple rhythmic repeats. Complex delay patterns.",
    tags: ["rhythmic", "complex", "ambient"],
  },
  {
    id: "crystal-delay",
    name: "Crystal Delay",
    category: "delay",
    basedOn: "CorOS pitch-shifted stereo delay",
    description:
      "Dual pitch-shifted repeats for polished shimmer, fusion, and ambient textures.",
    tags: ["coros-4.1", "stereo", "pitch", "ambient", "modern"],
    qcModelId: 6026,
    parameters: [
      position("MIX"),
      toggle("SYNC"),
      text("SYNC_NOTE_L"),
      text("SYNC_NOTE_R"),
      position("CRYSTAL_1_PAN"),
      position("CRYSTAL_2_PAN"),
      position("CRYSTAL_1_GAIN"),
      position("CRYSTAL_2_GAIN"),
      toggle("MODE"),
      position("FEEDBACK"),
      position("LOW_PASS"),
      position("HIGH_PASS"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "arpeggio-delay",
    name: "Arpeggio Delay",
    category: "delay",
    basedOn: "CorOS intelligent multi-tap pitch delay",
    description:
      "Key-aware pitched taps for rhythmic harmony and cinematic arpeggios.",
    tags: ["coros-4.1", "pitch", "rhythmic", "ambient", "experimental"],
    qcModelId: 6031,
    parameters: [
      position("MIX"),
      toggle("SYNC"),
      text("KEY"),
      text("SCALE"),
      position("GLISSANDO"),
      toggle("TAP_1_ACTIVE"),
      text("TAP_1_INTERVAL"),
      text("TAP_1_SYNC_NOTE"),
      position("TAP_1_LEVEL"),
      position("TAP_1_PAN"),
      toggle("TAP_2_ACTIVE"),
      text("TAP_2_INTERVAL"),
      text("TAP_2_SYNC_NOTE"),
      position("TAP_2_LEVEL"),
      position("TAP_2_PAN"),
      position("FEEDBACK"),
      text("FEEDBACK_SYNC_NOTE"),
      position("HIGH_PASS"),
      position("LOW_PASS"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "rabea-atlas-delay",
    name: "Rabea Atlas Delay",
    category: "delay",
    basedOn: "Archetype Rabea X Atlas stereo delay",
    description:
      "Dual stereo delay with cross-feedback, filtered repeats, and optional pitched icicles.",
    tags: ["rabea-x", "plugin", "stereo", "ambient", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 6030,
    parameters: [
      position("MIX"),
      toggle("SYNC"),
      position("DELAY_TIME_L"),
      position("DELAY_TIME_R"),
      text("SYNC_NOTE_L"),
      text("SYNC_NOTE_R"),
      position("FEEDBACK"),
      position("CROSS_FEED"),
      text("MODE"),
      position("ICICLES"),
      position("LOW_PASS"),
      position("HIGH_PASS"),
      toggle("TRAILS"),
    ],
  },

  // ===== REVERB =====
  {
    id: "hall-reverb",
    name: "Hall Reverb",
    category: "reverb",
    basedOn: "Concert Hall",
    description: "Large space reverb. Rich, immersive ambient wash.",
    tags: ["hall", "large", "ambient", "lush"],
    qcModelId: 8003,
    parameters: STANDARD_REVERB,
  },
  {
    id: "plate-reverb",
    name: "Plate Reverb",
    category: "reverb",
    basedOn: "EMT 140 Plate",
    description: "Bright, smooth reverb. Studio standard for vocals and guitar.",
    tags: ["plate", "bright", "smooth", "studio"],
    qcModelId: 8013,
    parameters: [
      position("MIX"),
      position("DECAY"),
      position("PRE_DELAY"),
      position("HIGH_PASS"),
      position("LOW_PASS"),
      position("MOD_DEPTH"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "room-reverb",
    name: "Room Reverb",
    category: "reverb",
    basedOn: "Small Room",
    description: "Natural, close room ambience. Adds space without drowning tone.",
    tags: ["room", "natural", "subtle"],
    qcModelId: 8000,
    parameters: STANDARD_REVERB,
  },
  {
    id: "spring-reverb",
    name: "Spring Reverb",
    category: "reverb",
    basedOn: "Fender Spring Reverb",
    description: "Classic drip and splash. Vintage surf and country tones.",
    tags: ["spring", "vintage", "surf", "drip"],
    qcModelId: 8006,
    parameters: [
      position("MIX"),
      position("DAMPING"),
      position("TONE"),
      position("BOING"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "shimmer-reverb",
    name: "Shimmer Reverb",
    category: "reverb",
    basedOn: "Pitch-shifted Shimmer",
    description: "Octave-up reverb tails. Ethereal, pad-like ambient textures.",
    tags: ["shimmer", "ambient", "ethereal", "pad"],
    qcModelId: 8010,
    parameters: [
      position("MIX"),
      position("DECAY"),
      position("BRIGHTNESS"),
      position("FEEDBACK"),
      position("PITCH"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "cave-reverb",
    name: "Cave Reverb",
    category: "reverb",
    basedOn: "Cavernous Space",
    description: "Massive, dark reverb. Long tails for atmospheric playing.",
    tags: ["cave", "dark", "massive", "atmospheric"],
    qcModelId: 8009,
    parameters: [
      position("DECAY"),
      position("PRE_DELAY"),
      position("DAMPING"),
      position("HIGH_PASS"),
      position("LOW_PASS"),
      position("MIX"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "vintage-digital",
    name: "Vintage Digital",
    category: "reverb",
    basedOn: "Vintage studio digital reverb",
    description:
      "Smooth late-80s/90s studio space with modulation, filtering, and freeze.",
    tags: ["coros-4.1", "vintage", "digital", "studio", "ambient"],
    qcModelId: 8039,
    parameters: [
      position("MIX"),
      position("SIZE"),
      position("PRE_DELAY"),
      position("DECAY"),
      position("HF_DAMPING"),
      position("MODULATION"),
      position("HIGH_PASS"),
      position("LOW_PASS"),
      toggle("FREEZE"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "rabea-aeons-reverb",
    name: "Rabea Aeons Reverb",
    category: "reverb",
    basedOn: "Archetype Rabea X Aeons reverb",
    description:
      "Expansive filtered reverb with pitchable freeze for self-accompanied ambient performance.",
    tags: ["rabea-x", "plugin", "freeze", "ambient", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 8036,
    parameters: [
      position("MIX"),
      position("DECAY"),
      position("PRE_DELAY"),
      position("LOW_PASS"),
      position("HIGH_PASS"),
      toggle("FREEZE"),
      position("FREEZE_PITCH"),
      position("FREEZE_VOLUME"),
      toggle("TRAILS"),
    ],
  },

  // ===== MODULATION =====
  {
    id: "chorus-ce1",
    name: "Chorus CE-1",
    category: "modulation",
    basedOn: "Boss CE-1 Chorus Ensemble",
    description: "Vintage analog chorus. Warm, rich doubling effect.",
    tags: ["chorus", "vintage", "warm", "analog"],
    qcModelId: 7000,
    parameters: [
      position("MIX"),
      toggle("MODE"),
      position("CHR_RATE"),
      position("VIB_RATE"),
      position("VIB_DEPTH"),
      position("WIDTH"),
      toggle("SYNC"),
    ],
  },
  {
    id: "chorus-dimension",
    name: "Chorus Dimension",
    category: "modulation",
    basedOn: "Roland Dimension D / Boss DC-2",
    description: "Subtle, lush stereo widening. Studio-grade chorus.",
    tags: ["chorus", "stereo", "subtle", "studio"],
  },
  {
    id: "flanger-classic",
    name: "Flanger",
    category: "modulation",
    basedOn: "Classic Flanger",
    description: "Jet-like swooshing. Classic modulation effect.",
    tags: ["flanger", "jet", "swoosh"],
    qcModelId: 7003,
    parameters: [
      position("MIX"),
      position("RATE"),
      position("DEPTH"),
      position("FEEDBACK"),
      position("WIDTH"),
      toggle("SYNC"),
    ],
  },
  {
    id: "phaser-90",
    name: "Phaser 90",
    category: "modulation",
    basedOn: "MXR Phase 90",
    description: "Classic 4-stage phaser. Swirling, watery modulation.",
    tags: ["phaser", "classic", "swirl"],
    qcModelId: 7028,
    parameters: [
      position("MIX"),
      position("SPEED"),
      toggle("SYNC"),
      toggle("TYPE"),
      toggle("MODE"),
    ],
  },
  {
    id: "tremolo",
    name: "Tremolo",
    category: "modulation",
    basedOn: "Fender Tremolo",
    description: "Volume modulation. Vintage amp-style pulsing effect.",
    tags: ["tremolo", "vintage", "pulse"],
    qcModelId: 7004,
    parameters: [
      position("RATE"),
      position("DEPTH"),
      position("DUTY_CYCLE"),
      position("SMOOTHING"),
      toggle("SYNC"),
    ],
  },
  {
    id: "vibrato",
    name: "Vibrato",
    category: "modulation",
    basedOn: "Pitch Vibrato",
    description: "Pitch modulation. Subtle to extreme pitch wobble.",
    tags: ["vibrato", "pitch", "wobble"],
    qcModelId: 7002,
    parameters: [
      position("RATE"),
      position("DEPTH"),
      position("WIDTH"),
      toggle("SYNC"),
    ],
  },
  {
    id: "rotary",
    name: "Rotary",
    category: "modulation",
    basedOn: "Leslie 122 Rotary Speaker",
    description: "Spinning speaker simulation. Classic organ and guitar effect.",
    tags: ["rotary", "leslie", "spin", "organ"],
    qcModelId: 7008,
    parameters: [
      toggle("SPEED"),
      position("SLOW_SPEED"),
      position("FAST_SPEED"),
      position("ACCELERATION"),
      position("DRIVE"),
      position("BRIGHTNESS"),
    ],
  },
  {
    id: "uni-vibe",
    name: "Uni-Vibe",
    category: "modulation",
    basedOn: "Shin-Ei Uni-Vibe",
    description: "Photocell modulation. Hendrix and Gilmour's psychedelic swirl.",
    tags: ["univibe", "psychedelic", "hendrix", "gilmour"],
    qcModelId: 7029,
    parameters: [
      position("MIX"),
      toggle("VIBE"),
      position("SPEED"),
      position("LEVEL"),
      position("DEPTH"),
      toggle("SYNC"),
    ],
  },
  {
    id: "glitch",
    name: "Glitch",
    category: "modulation",
    basedOn: "CorOS granular morph effect",
    description:
      "Tempo-aware granular repeats, interference, and textural transformations.",
    tags: ["coros-4.1", "granular", "glitch", "experimental", "rhythmic"],
    qcModelId: 26005,
    parameters: [
      text("MODE"),
      toggle("SYNC_SOURCE"),
      position("BLOCK_TEMPO"),
      position("MIX"),
      position("FILTER"),
      text("LOOP_LENGTH"),
      text("READ_POINT"),
      text("GRAIN_LENGTH"),
      text("G_OCCURRENCE"),
      position("PITCH_AMT"),
      text("PITCH_PATTERN"),
      position("CHAOS"),
      toggle("TRAILS"),
    ],
  },
  {
    id: "ring-modulator",
    name: "Ring Modulator",
    category: "modulation",
    basedOn: "CorOS pitch-tracking ring modulator",
    description:
      "From harmonic metallic color to deliberately inharmonic experimental tones.",
    tags: ["coros-4.1", "ring-mod", "experimental", "pitch-tracking"],
    qcModelId: 26006,
    parameters: [
      position("MIX"),
      toggle("PITCH_TRACKER"),
      position("FREQUENCY"),
      text("MULTIPLIER"),
      position("OFFSET"),
      position("OUTPUT"),
    ],
  },

  // ===== COMPRESSOR =====
  {
    id: "studio-comp",
    name: "Studio Comp",
    category: "compressor",
    basedOn: "Studio VCA Compressor",
    description: "Transparent studio compression. Even dynamics without coloring.",
    tags: ["transparent", "studio", "vca"],
  },
  {
    id: "optical-comp",
    name: "Optical Comp",
    category: "compressor",
    basedOn: "Optical Compressor (LA-2A style)",
    description: "Smooth, musical compression. Slow attack, natural feel.",
    tags: ["optical", "smooth", "musical"],
  },
  {
    id: "ross-comp",
    name: "Ross Comp",
    category: "compressor",
    basedOn: "Ross Compressor / Dyna Comp",
    description: "Classic guitar compressor. Sustain and squash for country/funk.",
    tags: ["classic", "sustain", "country", "funk"],
  },
  {
    id: "douglas-shining-comp-m",
    name: "Douglas Shining Comp (M)",
    category: "compressor",
    basedOn: "Darkglass Hyper Luminal",
    description:
      "Modern parallel compressor with fast control and transparent punch.",
    tags: ["coros-4.1", "parallel", "modern", "studio", "punch"],
    qcModelId: 5025,
    parameters: [
      position("INPUT"),
      text("RATIO"),
      position("ATTACK"),
      position("RELEASE"),
      position("MAKEUP"),
      position("MIX"),
    ],
  },
  {
    id: "rabea-twin-blade-compressor",
    name: "Rabea Twin Blade Dual Compressor",
    category: "compressor",
    basedOn: "Archetype Rabea X Twin Blade dual compressor",
    description:
      "Parallel two-stage compressor for controlled sustain with a preserved dry attack.",
    tags: ["rabea-x", "plugin", "parallel", "sustain", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 5028,
    parameters: [
      position("DRY"),
      position("IN"),
      position("ATT_REL_1"),
      position("THRU"),
      position("ATT_REL_2"),
      position("OUT"),
    ],
  },

  // ===== EQ =====
  {
    id: "parametric-eq",
    name: "Parametric EQ",
    category: "eq",
    basedOn: "Parametric Equalizer",
    description: "Surgical tone shaping. Adjustable frequency, gain, and Q.",
    tags: ["parametric", "surgical", "precise"],
  },
  {
    id: "graphic-eq",
    name: "Graphic EQ",
    category: "eq",
    basedOn: "10-Band Graphic EQ",
    description: "Visual frequency control. Quick tone shaping across bands.",
    tags: ["graphic", "visual", "bands"],
  },
  {
    id: "plugin-parametric-4",
    name: "Plugin Parametric-4",
    category: "eq",
    basedOn: "CorOS four-band plugin-style equalizer",
    description:
      "Camera-ready high/low filtering with four broad musical EQ bands.",
    tags: ["coros-4.1", "parametric", "studio", "filter", "recording"],
    qcModelId: 4008,
    parameters: [
      position("HPF"),
      position("LO_GAIN"),
      position("LO_FREQ"),
      position("LO_MID_GAIN"),
      position("LO_MID_FREQ"),
      position("HI_MID_GAIN"),
      position("HI_MID_FREQ"),
      position("HI_GAIN"),
      position("HI_FREQ"),
      position("LPF"),
    ],
  },

  // ===== PITCH =====
  {
    id: "pitch-shifter",
    name: "Pitch Shifter",
    category: "pitch",
    basedOn: "Pitch Shifter",
    description: "Shift pitch up or down. Harmonizer and octave effects.",
    tags: ["pitch", "harmony", "octave"],
  },
  {
    id: "poly-octaver",
    name: "Poly Octaver",
    category: "pitch",
    basedOn: "Polyphonic Octaver",
    description: "Polyphonic octave tracking. Clean sub-octave and upper octave.",
    tags: ["octave", "polyphonic", "sub", "upper"],
  },
  {
    id: "whammy",
    name: "Whammy",
    category: "pitch",
    basedOn: "Digitech Whammy",
    description: "Expression-controlled pitch shift. Dive bombs and harmonics.",
    tags: ["whammy", "expression", "pitch-bend"],
  },
  {
    id: "multivoicer",
    name: "Multivoicer",
    category: "pitch",
    basedOn: "CorOS four-voice intelligent harmonizer",
    description:
      "Four intelligent voices for harmony, detuned width, and modern ensemble textures.",
    tags: ["coros-4.1", "harmony", "unison", "stereo", "modern"],
    qcModelId: 18012,
    parameters: [
      position("DI_LEVEL"),
      text("KEY"),
      text("SCALE"),
      toggle("QUANTIZE"),
      toggle("V1_ACTIVE"),
      position("V1_LEVEL"),
      text("V1_INTERVAL"),
      position("V1_DETUNE"),
      position("V1_DELAY"),
      position("V1_PAN"),
      toggle("V2_ACTIVE"),
      position("V2_LEVEL"),
      text("V2_INTERVAL"),
      position("V2_DETUNE"),
      position("V2_DELAY"),
      position("V2_PAN"),
      position("HIGH_PASS"),
      position("LOW_PASS"),
      position("TONE"),
      position("GLISSANDO"),
      position("UNISON"),
      position("WIDTH"),
      position("OUTPUT"),
    ],
  },
  {
    id: "rabea-chaos-bed-octaver",
    name: "Rabea Chaos Bed Octaver",
    category: "pitch",
    basedOn: "Archetype Rabea X Chaos Bed octaver",
    description:
      "Blendable octave-up and octave-down voices with modern or vintage tracking character.",
    tags: ["rabea-x", "plugin", "octave", "experimental", "modern"],
    requiresPlugin: "archetype-rabea-x",
    qcModelId: 18017,
    parameters: [
      position("OCT_UP"),
      position("OCT_DWN"),
      position("DIRECT_LEVEL"),
      text("MODE"),
    ],
  },

  // ===== SYNTH =====
  {
    id: "rabea-overlord-synth",
    name: "Overlord Synth",
    category: "synth",
    basedOn: "Archetype Rabea X Overlord monosynth",
    description:
      "Guitar-tracked dual-oscillator synthesizer for bass, pad, lead, and arpeggiated layers.",
    tags: ["rabea-x", "plugin", "synth", "pad", "solo-performance"],
    qcModelId: 30001,
    parameters: [
      position("MIX"),
      position("SENSITIVITY"),
      toggle("ENV_RETRIGGER"),
      position("TUNING"),
      toggle("QUANTIZE"),
      text("ROOT"),
      text("SCALE"),
      toggle("SYNTH_ACTIVE"),
      position("SYNTH_LEVEL"),
      toggle("OSC1_ACTIVE"),
      text("OSC1_WAVE"),
      position("OSC_1_LEVEL"),
      position("OSC_1_STEPS"),
      position("OSC_1_DETUNE"),
      toggle("OSC2_ACTIVE"),
      text("OSC2_WAVE"),
      position("OSC_2_LEVEL"),
      position("OSC_2_STEPS"),
      position("OSC_2_DETUNE"),
      text("UNISON_SOURCE"),
      text("UNI_AMOUNT"),
      position("UNI_DETUNE"),
      position("UNI_WIDTH"),
      toggle("FILTER"),
      text("SLOPE"),
      position("CUTOFF"),
      position("RESONANCE"),
      position("DRIVE"),
      position("ENV_DCY_ATCK"),
      position("ENV_SUSTAIN"),
      position("GATE"),
      position("OUTPUT"),
    ],
  },

  // ===== WAH =====
  {
    id: "cry-baby",
    name: "Cry Baby",
    category: "wah",
    basedOn: "Dunlop Cry Baby GCB95",
    description: "Classic wah. Funky, vocal-like sweep.",
    tags: ["wah", "classic", "funk", "vocal"],
  },
  {
    id: "fasel-wah",
    name: "Fasel Wah",
    category: "wah",
    basedOn: "Dunlop Fasel Inductor Wah",
    description: "Vintage Fasel inductor wah. Smoother, more vocal sweep.",
    tags: ["wah", "vintage", "smooth", "vocal"],
  },

  // ===== NOISE GATE =====
  {
    id: "adaptive-gate-sc",
    name: "Adaptive Gate (S/C)",
    category: "gate",
    basedOn: "Quad Cortex adaptive sidechain noise reduction",
    description:
      "Adaptive noise reduction keyed from a selectable clean source so sustain survives post-amp gating.",
    tags: ["adaptive", "sidechain", "noise", "sustain", "recording"],
    qcModelId: 16007,
    parameters: [position("NOISE_REDUCTION"), text("SOURCE")],
  },
  {
    id: "noise-gate",
    name: "Noise Gate",
    category: "gate",
    basedOn: "Noise Gate",
    description: "Eliminates unwanted noise. Essential for high-gain tones.",
    tags: ["gate", "noise", "high-gain"],
    qcModelId: 16003,
    parameters: [position("THRESHOLD")],
  },

  // ===== CABINETS =====
  {
    id: "cab-4x12-brit",
    name: "4x12 Brit V30",
    category: "cab",
    basedOn: "Marshall 1960A with Celestion V30",
    description: "Classic British 4x12. Tight mids, controlled low end.",
    tags: ["4x12", "british", "v30", "marshall", "rock", "metal"],
    qcModelId: 12029,
    parameters: CAB_CONTROLS,
  },
  {
    id: "cab-4x12-brit-g25",
    name: "4x12 Brit G25",
    category: "cab",
    basedOn: "Marshall 1960A with Celestion G12M Greenback",
    description: "Greenback-loaded 4x12. Classic rock crunch, softer highs.",
    tags: ["4x12", "british", "greenback", "classic-rock"],
    qcModelId: 12005,
    parameters: CAB_CONTROLS,
  },
  {
    id: "cab-2x12-us",
    name: "2x12 US C12",
    category: "cab",
    basedOn: "Fender Twin 2x12 with Jensen C12",
    description: "Open-back Fender 2x12. Clean, scooped, with sparkle.",
    tags: ["2x12", "american", "fender", "clean", "open-back"],
    qcModelId: 12022,
    parameters: CAB_CONTROLS,
  },
  {
    id: "cab-1x12-us-dlx",
    name: "1x12 US DLX",
    category: "cab",
    basedOn: "Fender Deluxe 1x12",
    description: "Small Fender combo speaker. Warm, compressed at volume.",
    tags: ["1x12", "american", "fender", "warm"],
    qcModelId: 12017,
    parameters: CAB_CONTROLS,
  },
  {
    id: "cab-4x12-uber",
    name: "4x12 Uber",
    category: "cab",
    basedOn: "Bogner 4x12 Ubercab",
    description: "Tight, focused 4x12. Designed for high-gain clarity.",
    tags: ["4x12", "bogner", "tight", "high-gain"],
    qcModelId: 12035,
    parameters: CAB_CONTROLS,
  },
  {
    id: "cab-2x12-vox",
    name: "2x12 UK Blue",
    category: "cab",
    basedOn: "Vox AC30 2x12 Blue Alnico",
    description: "Alnico Blue speakers. Chimey, jangly Vox character.",
    tags: ["2x12", "vox", "alnico", "chime", "jangle"],
    qcModelId: 12013,
    parameters: CAB_CONTROLS,
  },
  {
    id: "cab-4x12-mesa-recto",
    name: "4x12 CA Recto",
    category: "cab",
    basedOn: "Mesa Boogie Rectifier 4x12",
    description: "Mesa Recto cab. Deep low end, aggressive mids for metal.",
    tags: ["4x12", "mesa", "rectifier", "metal", "deep"],
    qcModelId: 12001,
    parameters: CAB_CONTROLS,
  },
  {
    id: "ir-loader",
    name: "IR Loader",
    category: "cab",
    basedOn: "Impulse Response Loader",
    description: "Load custom IRs. Use third-party cabinet impulse responses.",
    tags: ["ir", "custom", "impulse-response"],
    qcModelId: 29001,
    parameters: [text("IR_PATH", 2)],
    generatable: false,
  },
];

export function getDevicesByCategory(category: DeviceCategory): Device[] {
  return QC_DEVICES.filter((d) => d.category === category);
}

export function getDeviceById(id: string): Device | undefined {
  return QC_DEVICES.find((d) => d.id === id);
}

export function getAllDeviceNames(): string[] {
  return QC_DEVICES.map((d) => `${d.name} (${d.basedOn})`);
}

export function getDeviceListForPrompt(
  ownedPlugins: readonly TonePluginLicense[] = [],
): string {
  const enabledPlugins = new Set(ownedPlugins);
  const categories = [
    "amp",
    "cab",
    "drive",
    "delay",
    "reverb",
    "modulation",
    "compressor",
    "eq",
    "pitch",
    "synth",
    "wah",
    "gate",
  ] as DeviceCategory[];

  return categories
    .map((cat) => {
      const devices = getDevicesByCategory(cat).filter(
        (device) =>
          device.qcModelId !== undefined &&
          device.parameters !== undefined &&
          device.generatable !== false &&
          (!device.requiresPlugin || enabledPlugins.has(device.requiresPlugin)),
      );
      if (devices.length === 0) return "";
      const header = cat.toUpperCase() + "S";
      const list = devices
        .map((device) => {
          const controls = device.parameters!
            .map(
              (parameter) =>
                `${parameter.name}:${parameter.kind === "switch" ? "boolean" : parameter.kind === "text" ? "text" : "0-100"}`,
            )
            .join(", ");
          return `  - ${device.name} [id: ${device.id}] | controls: ${controls || "none"} | ${device.description}`;
        })
        .join("\n");
      return `### ${header}\n${list}`;
    })
    .filter(Boolean)
    .join("\n\n");
}
